// Generated by CoffeeScript 1.6.3
var CatTimeline, fromPrototype;

fromPrototype = function(el) {
  return {
    prototype: Object.create(el.prototype)
  };
};

CatTimeline = document.registerElement('cat-timeline', fromPrototype(HTMLElement));

CatTimeline = document.registerElement('cat-grid', fromPrototype(HTMLElement));

CatTimeline = document.registerElement('cat-gridline', fromPrototype(HTMLElement));

CatTimeline = document.registerElement('cat-animations', fromPrototype(HTMLElement));

CatTimeline = document.registerElement('cat-animation', fromPrototype(HTMLElement));

CatTimeline = document.registerElement('cat-selector', fromPrototype(HTMLHeadingElement));

CatTimeline = document.registerElement('cat-keyframes', fromPrototype(HTMLElement));

CatTimeline = document.registerElement('cat-keyframe', fromPrototype(HTMLElement));

CatTimeline = document.registerElement('cat-name', fromPrototype(HTMLHeadingElement));

CatTimeline = document.registerElement('cat-time', fromPrototype(HTMLHeadingElement));

CatTimeline = document.registerElement('cat-properties', fromPrototype(HTMLElement));

CatTimeline = document.registerElement('cat-controls', fromPrototype(HTMLElement));
