// Generated by CoffeeScript 1.6.3

/*

1. Construct the timeline without animations.
2. Hook up event listeners.
   a. Horizontal scrolling.
   b. Scrubbing.
3. Parse all keyframe animations on parent page.
4. Search for selectors with animation property specified.
5. Add a row for each selector and keyframes for each animation specified.
*/

